
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: lets-enc-prod
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: {{MAIL}}

    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: lets-enc-prod

    # ACME DNS-01 provider configurations
    dns01:
      # Here we define a list of DNS-01 providers that can solve DNS challenges
      providers:
        - name: cf-dns-prod
          cloudflare:
            email: {{MAIL}}
            # A secretKeyRef to a cloudflare api key
            apiKeySecretRef:
              name: clf-api-key
              key: api-key
    solvers:
    - dns01:
        # Adjust the configuration below according to your environment.
        # You can view more example configurations for different DNS01
        # providers in the documentation: https://docs.cert-manager.io/en/latest/tasks/issuers/setup-acme/dns01/index.html
        cloudflare:
          email: {{MAIL}}
          apiKeySecretRef:
            name: clf-api-key
            key: api-key