apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: whoareyou-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: whoareyou
  template:
    metadata:
      labels:
        app: whoareyou
    spec:
      containers:
      - name: whoareyou-container
        image: containous/whoami
---
apiVersion: v1
kind: Service
metadata:
  name: whoareyou-service
  namespace: default
spec:
  ports:
  - name: http
    targetPort: 80
    port: 80
  selector:
    app: whoareyou
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: whoareyou-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true" 

spec:
  tls:
  - hosts:
    - {{DOMAIN_NAME}}
    secretName: {{DOMAIN_NICE}}-tls-prod
  rules:
  - host: whoareyou.{{DOMAIN_NAME}}
    http:
      paths:
      - path: /
        backend:
          serviceName: whoareyou-service
          servicePort: http