apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: node-example-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-example
  template:
    metadata:
      labels:
        app: node-example
    spec:
      containers:
      - name: node-example-container
        image: theykk/node-example-docker
---
apiVersion: v1
kind: Service
metadata:
  name: node-example-service
  namespace: default
spec:
  ports:
  - name: http
    targetPort: 8080
    port: 80
  selector:
    app: node-example
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: node-example-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true" 
spec:
  tls:
  - hosts:
    - {{DOMAIN_NAME}}
    secretName: {{DOMAIN_NICE}}-tls-prod
  rules:
  - host: node-example.{{DOMAIN_NAME}}
    http:
      paths:
      - path: /
        backend:
          serviceName: node-example-service
          servicePort: http
