apiVersion: k3s.cattle.io/v1
kind: HelmChart
metadata:
  name: traefik
  namespace: kube-system
spec:
  chart: stable/traefik
  set:
    rbac.enabled: "true"
    ssl.enabled: "true"
    dashboard.enabled: "true"
    dashboard.domain: "dashboard.{{HOST}}"
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dashboard-ingress
  namespace: kube-system
  annotations:
    certmanager.k8s.io/cluster-issuer: letsencrypt-staging
    kubernetes.io/ingress.class: traefik
spec:
  tls:
  - hosts:
    - dashboard.{{HOST}}
    secretName: dashboard-service-crt
  rules:
  - host: dashboard.{{HOST}}
    http:
      paths:
      - path: /
        backend:
          serviceName: dashboard-service
          servicePort: http
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-conf-external
  namespace: kube-system
data:
  traefik.toml: |
    defaultEntryPoints = ["http","https"]
    debug = false
    logLevel = "INFO"
    #Config to redirect http to https
    [entryPoints]
      [entryPoints.http]
        address = ":80"
        compress = true
        [entryPoints.http.redirect]
        entryPoint = "https"
      [entryPoints.https]
        address = ":443"
        compress = true
        [entryPoints.https.tls]
    [api]
      [api.statistics]
        recentErrors = 10
    [kubernetes]
      # Only create ingresses where the object has traffic-type: external label
      labelselector = "traffic-type=external"
    [metrics]
      [metrics.prometheus]
      buckets=[0.1,0.3,1.2,5.0]
      entryPoint = "traefik"
    [ping]
      entryPoint = "http"
    [accessLog]

    [acme]
      email = "yusufkaan142@gmail.com"
      storage = "traefik-external-certificates/acme/account"
      acmeLogging = true
      entryPoint = "https"
      OnHostRule = true
      #caServer = "https://acme-v02.api.letsencrypt.org/directory"
      [acme.httpChallenge]
        entryPoint="http"
---        
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: dashboard-service-crt
spec:
  secretName: dashboard-service-crt
  dnsNames:
  - dashboard.{{HOST}}
  acme:
    config:
    - http01:
        ingressClass: traefik
      domains:
      - dashboard.{{HOST}}
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
